Escuela.Mvc/Models/ErrorViewModel.cs
using System;

namespace Escuela.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Escuela.Mvc/ViewModels/VMAlumno.cs
using Escuela.Core;
using System.Collections.Generic;

namespace Escuela.Mvc.ViewModels
{
    public class VMAlumno
    {
        public IEnumerable<Curso> Cursos { get; set; }
        public Alumno Alumno { get; set; }
        public int? IdCursoSeleccionado { get; set; }
        public VMAlumno() => Alumno = new Alumno();
        public VMAlumno(IEnumerable<Curso> cursos) : this()
            => Cursos = cursos;
        public VMAlumno(Alumno alumno)
        {
            Alumno = alumno;            
        }
    }
}

Escuela.Mvc/Controllers/AlumnoController.cs
using Microsoft.AspNetCore.Mvc;
using Escuela.Core;
using Escuela.Mvc.ViewModels;

namespace Escuela.Controllers
{
    public class AlumnoController : Controller
    {
        [HttpGet]
        public IActionResult Index()
         => View(Repositorio.Alumno);

        [HttpGet]
        public IActionResult FormAlta()
        {
            var vmAlumno = new VMAlumno(Repositorio.Cursos);
            return View(vmAlumno);
        }

        [HttpPost]
        public IActionResult FormAlta(VMAlumno vMAlumno)
        {
            var curso = Repositorio.GetCurso(vMAlumno.IdCursoSeleccionado.Value);
            vMAlumno.Alumno.curso = curso;
            Repositorio.AgregarAlumno(vMAlumno.Alumno);
            return RedirectToAction("Index");
        }

    }
}

Escuela.Mvc/Controllers/CursoController.cs
using Microsoft.AspNetCore.Mvc;
using Escuela.Core;

namespace Escuela.Controllers
{
    public class CursoController : Controller
    {
        [HttpGet]
        public IActionResult Index()
         => View(Repositorio.Curso); 

        [HttpGet]
        public IActionResult FormAlta() => View();

        [HttpPost]
        public IActionResult FormAlta(Curso curso)
        {
            Repositorio.AgregarCurso(curso);
            return View("Index", Repositorio.Curso);
        }

    }
}

Escuela.Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Escuela.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Escuela.Mvc/Views/Alumno/FormAlta.cshtml
@model Escuela.Mvc.ViewModels.VMAlumno;
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Alumno</title>
</head>
<body>
    <form asp-action="FormAlta" method ="post">
        <div asp-validation-summary="All"></div>
        
        <div>
            <label asp-for="@Model.Alumno.Nombre">Nombre:</label>
            <input asp-for="@Model.Alumno.Nombre" />
        </div>

        <div>
            <label asp-for="@Model.Alumno.Apellido">Apellido:</label>
            <input asp-for="@Model.Alumno.Apellido" />
        </div>

        <div>
            <label asp-for="@Model.Alumno.DNI">DNI:</label>
            <input asp-for="@Model.Alumno.DNI" />
        </div>
    
        <div>
            <select asp-for="IdCursoSeleccionado">
                <option value="">Elegi un curso</option>
                @foreach (Escuela.Core.Curso curso in Model.Cursos)
                {
                    <option value="@curso.Id">@curso.Anio ° @curso.Division °</option>
                }
            </select>
        </div>

        <button type="submit">Alta Alumno</button>
    </form>

    <button>
    <a asp-controller="" asp-action="Index">Inicio</a>
    </button>
    
</body>
</html>

Escuela.Mvc/Views/Alumno/Index.cshtml
@model IEnumerable<Escuela.Core.Alumno>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Alumno</title>
</head>
<body>
    
    <h2>Alumno</h2>
    <table>
        <thead>
            <tr>  
                <td>Nombre</td> 
                <td>Apellido</td> 
                <td>Curso</td> 
            </tr>
        </thead>
        <tbody>
            @foreach (Escuela.Core.Alumno alumno in Model)
            {
                <tr>
                    <td><a asp-controller="Alumno" asp-action="Detalle" asp-route-id="@alumno.Id">@alumno.Nombre</a></td>
                    <td><a asp-controller="Alumno" asp-action="Detalle" asp-route-id="@alumno.Id">@alumno.Apellido</a></td>
                    <td><a asp-controller="Alumno" asp-action="Detalle" asp-route-id="@alumno.Id">@alumno.curso.Anio ° @alumno.curso.Division °</a></td>
                </tr>
            }
        </tbody>
    </table>

    <button>
    <a asp-controller="" asp-action="Index">Inicio</a>
    </button>
    
</body>
</html>

Escuela.Mvc/Views/Alumno/detalle.cshtml
@model Escuela.Core.Curso
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Alumno - Detalle @Model.Curso</title>
</head>
<body>
    <a asp-controller="Alumno" asp-action="FormAlta" asp-route-idCurso="@Model.Id">Alta Alumno</a> <br />
    <h5>Alumno</h5>
    <table>
        <thead>
            <tr>
                <td>Nombre</td>
                <td>Apellido</td>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>
</body>
</html>

Escuela.Mvc/Views/Curso/FormAlta.cshtml
@model Escuela.Core.Curso
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Curso</title>
</head>
<body>
    <form asp-action="FormAlta" method ="post">
        <div asp-validation-summary="All"></div>
        
        <div>
            <label asp-for="Anio">Año:</label>
            <input asp-for="Anio" />
        </div>

        <div>
            <label asp-for="Division">Division:</label>
            <input asp-for="Division" />
        </div>

         <div>
            <label asp-for="Turno">Turno:</label>
            <input asp-for="Turno" />
        </div>
        
        <button type="submit">Alta Curso</button>
    </form>

    <button>
    <a asp-controller="" asp-action="Index">Inicio</a>
    </button>
    
</body>
</html>

Escuela.Mvc/Views/Curso/Index.cshtml
@model IEnumerable<Escuela.Core.Curso>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Curso</title>
</head>
<body>
    
    <h2>Curso</h2>

    <table>
        <thead>
            <tr> 
                <td>Año</td> 
                <td>Division</td> 
                <td>Turno</td> 
            </tr>
        </thead>
        <tbody>
            @foreach (Escuela.Core.Curso curso in Model)
            {
                <tr>
                    <td><a asp-controller="Curso" asp-action="Detalle" asp-route-id="@curso.Id">@curso.Anio</a></td>
                    <td><a asp-controller="Curso" asp-action="Detalle" asp-route-id="@curso.Id">@curso.Division</a></td>
                    <td><a asp-controller="Curso" asp-action="Detalle" asp-route-id="@curso.Id">@curso.Turno</a></td>
                </tr>
            }
        </tbody>
    </table>

    <button>
    <a asp-controller="" asp-action="Index">Inicio</a>
    </button>
    
</body>
</html>

Escuela.Mvc/Views/Falta/FormAlta.cshtml
@model Escuela.Core.Falta
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Curso</title>
</head>
<body>
    
    <button>
    <a asp-controller="" asp-action="Index">Inicio</a>
    </button>
    
</body>
</html>

Escuela.Mvc/Views/Falta/Index.cshtml
@model IEnumerable<Escuela.Core.Falta>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Falta</title>
</head>
<body>
    
    <h2>Falta</h2>
    <table>
        <thead>
            <tr>  
                <td>Alumno</td> 
                <td>Falta</td> 
            </tr>
        </thead>
        <tbody>
            @foreach (Escuela.Core.Falta falta in Model)
            {
                <tr>
                    <td><a asp-controller="Falta" asp-action="Detalle" asp-route-id="@falta.Id">@falta.Alumno</a></td>
                    <td><a asp-controller="Falta" asp-action="Detalle" asp-route-id="@falta.Id">@falta.ValorFalta</a></td>
                </tr>
            }
        </tbody>
    </table>

    <button>
    <a asp-controller="" asp-action="Index">Inicio</a>
    </button>
    
</body>
</html>

Escuela.Mvc/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Escuela</title>
</head>
    <body>
        <a asp-controller="Curso" asp-action="FormAlta">Alta Cursos</a> <br/>

        <a asp-controller="Curso" asp-action="Index">Ver Cursos</a> <br/><br/>

        <a asp-controller="Alumno" asp-action="FormAlta">Alta Alumno</a> <br/>

        <a asp-controller="Alumno" asp-action="Index">Ver Alumno</a> <br/><br/>

        <a asp-controller="Falta" asp-action="Index">Ver Faltas</a> <br/><br/>

    </body>
</html>

Escuela.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Escuela.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Escuela.Mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Escuela.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>